export interface HaircutStyle {
  id: string;
  name: string;
  description: string;
  category: string;
  image: string;
  prompt: string;
}

export const HAIRCUT_CATEGORIES = [
  'All',
  'Custom',
  'Classic',
  'Modern',
  'Fade',
  'Long',
  'Textured',
  'Trending',
  'Beard Combo',
] as const;

export type HaircutCategory = (typeof HAIRCUT_CATEGORIES)[number];

export const CUSTOM_HAIRCUT: HaircutStyle = {
  id: 'custom',
  name: 'Custom',
  description: 'Describe your dream haircut and AI will create it',
  category: 'Custom',
  image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400&h=500&fit=crop',
  prompt: '',
};

export const HAIRCUTS: HaircutStyle[] = [
  CUSTOM_HAIRCUT,
  {
    id: 'buzz-cut',
    name: 'Buzz Cut',
    description: 'Clean and minimal all-over short cut',
    category: 'Classic',
    image: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=400&h=500&fit=crop',
    prompt: 'Apply a clean buzz cut hairstyle, very short uniform length all over, about 1/8 inch, neat and clean military-style buzz cut',
  },
  {
    id: 'crew-cut',
    name: 'Crew Cut',
    description: 'Short sides with slightly longer top',
    category: 'Classic',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop',
    prompt: 'Apply a classic crew cut hairstyle, short tapered sides with slightly longer hair on top brushed forward, clean and professional look',
  },
  {
    id: 'high-fade',
    name: 'High Fade',
    description: 'Sharp high fade with textured top',
    category: 'Fade',
    image: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=400&h=500&fit=crop',
    prompt: 'Apply a high fade haircut, skin fade starting high on the sides blending into longer textured hair on top, sharp and modern barbershop high fade',
  },
  {
    id: 'mid-fade',
    name: 'Mid Fade',
    description: 'Balanced mid-level fade transition',
    category: 'Fade',
    image: 'https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=400&h=500&fit=crop',
    prompt: 'Apply a mid fade haircut, gradual fade starting at mid-level of the sides, smooth transition from short to longer hair on top, clean mid fade barbershop cut',
  },
  {
    id: 'low-fade',
    name: 'Low Fade',
    description: 'Subtle fade near the neckline',
    category: 'Fade',
    image: 'https://images.unsplash.com/photo-1583195764036-6dc248ac07d9?w=400&h=500&fit=crop',
    prompt: 'Apply a low fade haircut, subtle gradual fade near the neckline and ears, keeping more length on the sides with a clean low taper fade',
  },
  {
    id: 'skin-fade',
    name: 'Skin Fade',
    description: 'Clean bald fade to skin on sides',
    category: 'Fade',
    image: 'https://images.unsplash.com/photo-1570158268183-d296b2892211?w=400&h=500&fit=crop',
    prompt: 'Apply a skin fade haircut, completely bald at the temples fading gradually up to longer hair on top, ultra clean skin fade barbershop cut',
  },
  {
    id: 'taper-fade',
    name: 'Taper Fade',
    description: 'Gradual taper with natural blend',
    category: 'Fade',
    image: 'https://images.unsplash.com/photo-1534030347209-467a5b0ad3e6?w=400&h=500&fit=crop',
    prompt: 'Apply a taper fade haircut, gradual natural taper from longer to shorter around the ears and neckline, clean and subtle taper fade',
  },
  {
    id: 'pompadour',
    name: 'Pompadour',
    description: 'Voluminous swept-back style',
    category: 'Modern',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=500&fit=crop',
    prompt: 'Apply a modern pompadour hairstyle, voluminous hair swept back and up on top with shorter faded sides, sleek and polished pompadour style',
  },
  {
    id: 'quiff',
    name: 'Quiff',
    description: 'Textured volume at the front',
    category: 'Modern',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=500&fit=crop',
    prompt: 'Apply a modern quiff hairstyle, longer textured hair at the front swept upward and back with shorter sides, stylish textured quiff with volume',
  },
  {
    id: 'slick-back',
    name: 'Slick Back',
    description: 'Smooth combed-back look',
    category: 'Classic',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=500&fit=crop',
    prompt: 'Apply a slick back hairstyle, hair combed smoothly backwards with a wet look finish, classic gentleman slicked back style with product shine',
  },
  {
    id: 'textured-crop',
    name: 'Textured Crop',
    description: 'Messy textured fringe forward',
    category: 'Textured',
    image: 'https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=400&h=500&fit=crop',
    prompt: 'Apply a textured crop hairstyle, short choppy textured hair on top with a messy fringe falling forward, modern French crop with textured finish',
  },
  {
    id: 'messy-fringe',
    name: 'Messy Fringe',
    description: 'Casual tousled front fringe',
    category: 'Textured',
    image: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=500&fit=crop',
    prompt: 'Apply a messy fringe hairstyle, tousled casual hair with a textured fringe falling across the forehead, effortless messy bedhead style',
  },
  {
    id: 'curtains',
    name: 'Curtain Hair',
    description: 'Center-parted flowing style',
    category: 'Long',
    image: 'https://images.unsplash.com/photo-1531891437562-4301cf35b7e4?w=400&h=500&fit=crop',
    prompt: 'Apply curtain hairstyle, medium length hair parted in the center flowing to both sides like curtains, 90s inspired center-part curtain bangs style',
  },
  {
    id: 'man-bun',
    name: 'Man Bun',
    description: 'Long hair tied up on top',
    category: 'Long',
    image: 'https://images.unsplash.com/photo-1480455624313-e29b44bbfde1?w=400&h=500&fit=crop',
    prompt: 'Apply a man bun hairstyle, long hair pulled back and tied into a neat bun at the back/top of the head, clean man bun with some face-framing strands',
  },
  {
    id: 'edgar-cut',
    name: 'Edgar Cut',
    description: 'Sharp straight fringe with high fade',
    category: 'Trending',
    image: 'https://images.unsplash.com/photo-1618886614638-80e3c103d31a?w=400&h=500&fit=crop',
    prompt: 'Apply an Edgar cut hairstyle, straight sharp fringe across the forehead with a high skin fade on the sides, clean Edgar/Takuache style cut',
  },
  {
    id: 'wolf-cut',
    name: 'Wolf Cut',
    description: 'Shaggy layered mullet-inspired style',
    category: 'Trending',
    image: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?w=400&h=500&fit=crop',
    prompt: 'Apply a wolf cut hairstyle, shaggy layered hair with volume on top and longer wispy layers around the sides and back, trendy wolf cut with texture and movement',
  },
  {
    id: 'burst-fade',
    name: 'Burst Fade',
    description: 'Rounded fade behind the ears',
    category: 'Trending',
    image: 'https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?w=400&h=500&fit=crop',
    prompt: 'Apply a burst fade haircut, rounded fade pattern radiating from behind the ear, longer curly or textured hair on top with clean burst fade on sides',
  },
  {
    id: 'mohawk-fade',
    name: 'Mohawk Fade',
    description: 'Wide strip on top with faded sides',
    category: 'Modern',
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=500&fit=crop',
    prompt: 'Apply a mohawk fade hairstyle, wider strip of longer hair running from front to back with faded sides, modern faux hawk with clean side fades',
  },
  {
    id: 'side-part',
    name: 'Side Part',
    description: 'Classic gentleman side part',
    category: 'Classic',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=500&fit=crop',
    prompt: 'Apply a classic side part hairstyle, hair neatly parted to one side with a clean hard part line, traditional gentlemen side part with tapered sides',
  },
  {
    id: 'ivy-league',
    name: 'Ivy League',
    description: 'Longer crew cut with side part',
    category: 'Classic',
    image: 'https://images.unsplash.com/photo-1548372290-8d01b6c8e78c?w=400&h=500&fit=crop',
    prompt: 'Apply an Ivy League haircut, a longer version of the crew cut with enough length on top to part to the side, clean collegiate preppy style',
  },
  {
    id: 'two-block',
    name: 'Two Block',
    description: 'Korean-inspired disconnected style',
    category: 'Trending',
    image: 'https://images.unsplash.com/photo-1614289371518-722f2615943d?w=400&h=500&fit=crop',
    prompt: 'Apply a two block haircut, Korean-inspired style with short buzzed sides and back disconnected from longer styled hair on top, clean K-pop two block cut',
  },
  {
    id: 'mullet-modern',
    name: 'Modern Mullet',
    description: 'Updated business-in-front party-in-back',
    category: 'Trending',
    image: 'https://images.unsplash.com/photo-1557862921-37829c790f19?w=400&h=500&fit=crop',
    prompt: 'Apply a modern mullet hairstyle, textured shorter front and sides with longer flowing hair in the back, trendy updated mullet with texture',
  },
  {
    id: 'undercut',
    name: 'Undercut',
    description: 'Disconnected shaved sides with length on top',
    category: 'Modern',
    image: 'https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=400&h=500&fit=crop',
    prompt: 'Apply an undercut hairstyle, dramatically short or shaved sides with a disconnected longer top that can be styled back or to the side, sharp modern undercut',
  },
  {
    id: 'spiky-hair',
    name: 'Spiky Hair',
    description: 'Textured spikes with product hold',
    category: 'Textured',
    image: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400&h=500&fit=crop',
    prompt: 'Apply a spiky hairstyle, short to medium hair spiked up with product for a textured edgy look, modern spiky hair with defined points',
  },
  {
    id: 'curly-top-fade',
    name: 'Curly Top Fade',
    description: 'Natural curls on top with clean fade',
    category: 'Textured',
    image: 'https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=400&h=500&fit=crop',
    prompt: 'Apply a curly top with fade haircut, natural tight curls on top with a clean mid to high fade on the sides, defined curly hair on top with sharp faded sides',
  },
  {
    id: 'flow-hair',
    name: 'Flow Hair',
    description: 'Medium length swept-back flowing hair',
    category: 'Long',
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=500&fit=crop',
    prompt: 'Apply a flow hairstyle, medium to long hair swept back and flowing naturally with volume and movement, hockey player flow hair style',
  },
  {
    id: 'top-knot',
    name: 'Top Knot',
    description: 'Long hair tied high with shaved sides',
    category: 'Long',
    image: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=500&fit=crop',
    prompt: 'Apply a top knot hairstyle, long hair on top tied into a tight knot at the crown with shaved or faded sides, clean samurai-inspired top knot',
  },
  {
    id: 'fade-beard-combo',
    name: 'Fade + Full Beard',
    description: 'High fade blended into a full beard',
    category: 'Beard Combo',
    image: 'https://images.unsplash.com/photo-1595152452543-e5fc28ebc2b8?w=400&h=500&fit=crop',
    prompt: 'Apply a high fade haircut that blends seamlessly into a thick full beard, the fade transitions into the beard line perfectly, groomed beard with sharp lineup',
  },
  {
    id: 'buzz-stubble',
    name: 'Buzz + Stubble',
    description: 'Buzz cut paired with heavy stubble',
    category: 'Beard Combo',
    image: 'https://images.unsplash.com/photo-1581803118522-7b72a50f7e9f?w=400&h=500&fit=crop',
    prompt: 'Apply a buzz cut with heavy stubble beard combo, very short buzz cut on head with well-groomed heavy stubble facial hair, rugged masculine look',
  },
  {
    id: 'taper-goatee',
    name: 'Taper + Goatee',
    description: 'Clean taper fade with shaped goatee',
    category: 'Beard Combo',
    image: 'https://images.unsplash.com/photo-1530268729831-4b0b9e170218?w=400&h=500&fit=crop',
    prompt: 'Apply a taper fade haircut with a well-shaped goatee, clean tapered sides with a neat goatee beard focused on chin and mustache area, sharp groomed look',
  },
];
